import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Doradas Pampeanas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthContextProvider>
        <Header />
          {children}
        <Footer/>
      </AuthContextProvider>
      </body>
    </html>
  );
}

